image: maven:3-jdk-11

stages:
  - build
  - test
  - deploy

before_script:
  - echo "DATA VALIDATION AND DATA INGESTION"
  - echo "CI/CD Pipeline"

build:
  stage: build
  tags:
    - $GITLAB_RUNNER
  script: "mvn clean install"

test:
  stage: test
  tags:
    - $GITLAB_RUNNER
  script: "mvn clean test"

after_script:
  - echo "Build and Test Done Successfully"

deploy:
  stage: deploy
  tags:
    - $GITLAB_RUNNER
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_DEVELOPEMENT  --api-key=$HEROKU_API_KEY
  only:
    - develop
